[package]
authors = ["chenyueban"]
default-run = "app"
description = "An open-source lightweight AI-powered memo hub."
edition = "2021"
license = ""
name = "app"
repository = ""
rust-version = "1.59"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
tauri-build = { version = "1.3.0", features = [] }

[dependencies]
arboard = "3.2.0"
clipboard = "0.5.0"
cpuid = "0.1.1"
enigo = { git = "https://github.com/enigo-rs/enigo" }
mouce = "0.2.41"
mouse_position = "0.1.3"
once_cell = "1.17.1"
parking_lot = "0.12.1"
rdev = "0.5.2"
sentry = "0.30.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sysinfo = "0.28.3"
tauri = { version = "1.3.0", features = ["clipboard-all", "dialog-message", "fs-read-dir", "fs-read-file", "fs-write-file", "global-shortcut-all", "http-all", "notification-all", "shell-open", "system-tray", "updater", "window-all", "windows7-compat"] }
tauri-plugin-autostart = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }
tauri-plugin-single-instance = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
tauri-plugin-deep-link = { git = "https://github.com/FabianLars/tauri-plugin-deep-link", branch = "main" }
tauri-plugin-window-state = "0.1.0"
whatlang = "0.16.2"
window-shadows = "0.2.1"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.24"
core-graphics = "0.22.3"
macos-accessibility-client = "0.0.1"
objc = "0.2.7"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.44.0", features = [
  "Win32_UI_WindowsAndMessaging",
  "Win32_Foundation"
] }

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]
